### PR TITLE
Caching, ajax_history, refactoring

### PR DESCRIPTION
**Pull request by pvbergen**
Changes in this PR:
- Caching the computed ids for filter items removal
- Add events to react to select2 initialization on advanced selects (select2options, iq_bef_extensions options)
- Support for views_ajax_history, which is also added as a new dependency
- Separating init and localstorage js files
- Refactoring filter plugins to allow granular overrides
- Add a counter_prefix text field to advanced-select

### CODE REVIEW

**Comment by pvbergen** [comment]
@danielwirz 
This should now be ready for review. I've updated the description to properly reflect all the changes

**Comment by danielwirz** [comment]
I encountered several issues while testing:

1. We need to make sure views_ajax_history is installed.
I could resolve this by adding an update_hook. [See Commit](https://github.com/iqual-ch/iq_bef_extensions/pull/9/commits/182faf50996cffeafc249fe1abbb516fbd8252e9) 

2. PHP Notice, when Ajax history is not enabled on view display.
_Notice: Undefined index: ajax_history in Drupal\iq_bef_extensions\Plugin\better_exposed_filters\filter\DefaultWidget->exposedFormAlter() (line 39 of modules/custom/iq_bef_extensions/src/Plugin/better_exposed_filters/filter/DefaultWidget.php)._

3. The slider plugin does not work with ajax history.
The slider plugin relies on the localstorage implementation, so it requires some rewriting.

**Comment by danielwirz** [comment]
The patch for #3090512 causes issues on range filters (See: https://www.drupal.org/project/views_ajax_history/issues/3090512#comment-15098324). I replaced it with a new version of the patch I submitted to drupal which should fix this issue.

**Comment by danielwirz** [comment]
I ran into another small issue where the preview values in the slider were not updated correctly / not shown when there were values set in the URL. however, i was able to fix for Max Urech ([487fdc0](https://github.com/iqual-ch/iq_bef_extensions/pull/9/commits/487fdc0ea5d7938f10571e108768d0aa9f636920)). On TOP Events, the preview values are now displayed always, even there's no value set. I'll look further into that.

Besides that, I did not find any other issues.

For the release/deployment, keep in mind that we need to manually set the "UEnable Views AJAX history." option on all view displays, see https://github.com/iqual-ch/iq_bef_extensions/blob/487fdc0ea5d7938f10571e108768d0aa9f636920/iq_bef_extensions.install#LL48C45-L48C45.

**Comment by danielwirz** [comment]
Fixed the issue with the preview values.

**Pull request closed without merging**
